Title =  "5分钟"
LanguageCode = "zh-CN"
BaseUrl = "http://blog.navee.cc/"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "zh"

[Params]
  Introduce = "每天5分钟"
  Description = "每天5分钟分享"
  Keywords =  "Navee,独立,博客,程序员,架构师,个人,思考,读书,笔记,技术,分享,Java"
  Subtitle = ""
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  RevolverMapId = "5b4f2ucxar6"
  Fancybox = true

[Author]
  Name = "Navee"

[Params.Share]
  #DuoShuo = "lanlingzi"
  Baidu = true

[Params.utterances]  # https://utteranc.es/
  owner = ""         # Your GitHub ID
  repo = ""          # The repo to store comments

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "技术"
  Pre = "code"
  URL = "/categories/技术/"
  Weight = 2

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/navee/"

